### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by sarhatabaot** [allquixotic/encuum#2]
When running encuum I get a 
`Parse error: invalid type: sequence, expected a map at line 1 column 76`

**Comment by allquixotic** [comment]
Hi,

I need more context. Are there any other lines logged before that, or is that the first thing that comes out of the console? Which .env options are you setting?

**Comment by sarhatabaot** [comment]
Sorry, it's the first thing that comes out of the console.
```
email=sarhatabaot1@gmail.com
password=*****
website=treasureisland.enjin.com
database_file=database.db
forum_ids=6095232
subforum_ids=3291782,2146987
session_id=*****
```

This is what I'm using, with the password & session id marked out obv.

**Comment by allquixotic** [comment]
Can you download [Proxyman](https://proxyman.io/), set it up to capture HTTPS traffic, and specify `proxy=http://127.0.0.1:9091` (for example; the port may differ on your end) in your .env file? This will allow Proxyman to capture the HTTP payload and response when you encounter the error.

Then you can copy and paste the HTTP request and resposne here, and just redact any sensitive info. Thanks!

**Comment by Zamotic** [comment]
I seem to also be getting a parse error:
```
got a post 49736750 related to thread 8735370
got a post 49736747 related to thread 8735370
Parse error: invalid type: null, expected a string at line 1 column 4454
```

I'll look into trying the proxyman post mentioned above, but I just wanted to give you a heads up initially.

**Comment by Zamotic** [comment]
Here's the request/response information via proxyman for the above issue:
[encuum - request_response.zip](https://github.com/allquixotic/encuum/files/10528109/encuum.-.request_response.zip)

**Comment by allquixotic** [comment]
@Zamotic , I deleted your comment because it contained an unredacted Session ID. Sorry for any confusion; that session ID needed to be removed from the request. I'm looking into your issue.

**Comment by Zamotic** [comment]
> @Zamotic , I deleted your comment because it contained an unredacted Session ID. Sorry for any confusion; that session ID needed to be removed from the request. I'm looking into your issue.

Honestly, I was going to edit the comment and remove the zip once you replied anyway.

**Comment by allquixotic** [comment]
I found the bug! I think this should be fixed in the latest master version of encuum. Can you please retest?

**Comment by allquixotic** [comment]
And I just pushed another fix as of 6:55pm Eastern today resolving a problem with the subforum DB inserts. This would break anyone's usage of the tool...

**Comment by Zamotic** [comment]
Looks good! It went for a good long while before hitting the next issue (RPC Call failed). This looks fixed for me.

**Comment by allquixotic** [comment]
Can you post the next RPC call failed error so I can look at it? Need to work out the kinks on getting the right data format in the schema.

**Comment by sarhatabaot** [comment]
Sorry for the late reply. 
With the latest code I'm still experiencing the same issue. 
```
[src\forum.rs:166] f = "Preset: 6095232, Try #1: Parse error: invalid type: sequence, expected a map at line 1 column 76"
[src\forum.rs:166] f = "Preset: 6095232, Try #2: Parse error: invalid type: sequence, expected a map at line 1 column 76"
[src\forum.rs:166] f = "Preset: 6095232, Try #3: Parse error: invalid type: sequence, expected a map at line 1 column 76"
[src\forum.rs:166] f = "Preset: 6095232, Try #4: Parse error: invalid type: sequence, expected a map at line 1 column 76"
`

I can't really figure out how to use proxyman as it breaks the certificate for the particular domain I'm trying to connect to. I'd appreciate some help setting this up!

**Comment by allquixotic** [comment]
Hi,

There is a good write-up for Proxyman in [README.md](https://github.com/allquixotic/encuum/blob/master/README.md now, but if you want, we can connect on Discord... friend me as Coorbin#0709 and we'll work it out.

**Comment by allquixotic** [comment]
Fixed: https://github.com/allquixotic/encuum/commit/ed14c161f40f86b7f3716dbc24b0b01a2cd82527

Can you please retest?

**If you cloned using Git:** Remove the file `Cargo.lock` in the encuum directory, then `git pull`.

**If you downloaded the Zip file:** Just download another version of the zip from the same link as in the readme. Discard your previous copy of encuum and try again.

**Comment by sarhatabaot** [comment]
Seems to work ok for me. 
Running a full archive to see if I get anymore errors.

**Comment by allquixotic** [comment]
Closing as fixed. Please open a new issue if you have any more problems.
